# Generated by Django 5.0.3 on 2024-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='employees',
            field=models.ManyToManyField(to='HotelApp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('r', 'recepcioner'), ('x', 'higienicar'), ('m', 'menadzer')], max_length=1),
        ),
    ]
